version: '3'
services:
  app:
    build: .
    network_mode: host
    ports:
      - "3009:3009"
      - "3099:3099"
    environment:
      - FEEDBACK_URL=
      - REDIRECT_TIMEOUT=10000
      - REDIRECT_URL=
      - SHARED_SECRET=
      - CHECKSUM_ALGORITHM=sha1
      - BASIC_URL=
      - API_PATH=/bigbluebutton/api/
      - CALLBACK_PATH=/feedback/webhook
      - LOG_LEVEL=info
      - LOG_STDOUT=true
      - PORT=3009
      - METRICS_PORT=3099
      - REDIS_HOST=localhost
      - REGISTER_HOOKS=false
